language: node_js

node_js:
  - 10

before_install:
  - npm i -g npm@6.9.0
  
install:
  - npm ci


script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  email: false